name: Lint JS and CSS files

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "37 21 * * 6"

jobs:
  ESLint:
    name: Check with ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: npm install

      - name: Run ESLint
        run: npm run lint:js
  Stylelint:
    name: Check with Stylelint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Stylelint
        run: npm install

      - name: Run Stylelint
        run: npm run lint:css
